###############################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

FROM openjdk:8-jre

# Install dependencies
RUN set -ex; \
  apt-get update; \
  apt-get -y install libsnappy1v5 gettext-base libjemalloc-dev; \
  rm -rf /var/lib/apt/lists/*

# Grab gosu for easy step-down from root
# Used by docker-entrypoint.sh
ENV GOSU_VERSION 1.11
RUN set -ex; \
  wget -nv -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)"; \
  wget -nv -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc"; \
  export GNUPGHOME="$(mktemp -d)"; \
  for server in ha.pool.sks-keyservers.net $(shuf -e \
                          hkp://p80.pool.sks-keyservers.net:80 \
                          keyserver.ubuntu.com \
                          hkp://keyserver.ubuntu.com:80 \
                          pgp.mit.edu) ; do \
      gpg --batch --keyserver "$server" --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && break || : ; \
  done && \
  gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
  gpgconf --kill all; \
  rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
  chmod +x /usr/local/bin/gosu; \
  gosu nobody true


# Prepare environment
ENV FLINK_HOME=/opt/flink
ENV PATH=$FLINK_HOME/bin:$PATH
RUN groupadd --system --gid=9999 flink && \
    useradd --system --home-dir $FLINK_HOME --uid=9999 --gid=flink flink
COPY flink-1.12.1-bin-scala_2.11.tgz $FLINK_HOME/flink.tgz
COPY flink-libs.tgz $FLINK_HOME/flink-libs.tgz

WORKDIR $FLINK_HOME

# Install Flink and create distro
RUN set -ex; \
  tar -xf flink.tgz --strip-components=1; \
  tar -xf flink-libs.tgz; \
  rm flink.tgz flink-libs.tgz; \
  ln -s opt/flink-shaded-netty-tcnative-dynamic-2.0.30.Final-12.0.jar lib/flink-shaded-netty-tcnative-dynamic-2.0.30.Final-12.0.jar; \
  ln -s opt/flink-queryable-state-runtime_2.11-1.12.1.jar lib/flink-queryable-state-runtime_2.11-1.12.1.jar; \
  ln -s opt/flink-cep_2.11-1.12.1.jar lib/flink-cep_2.11-1.12.1.jar; \
  mkdir plugins/azure-fs-hadoop; \
  ln -s opt/flink-azure-fs-hadoop-1.12.1.jar plugins/azure-fs-hadoop/flink-azure-fs-hadoop-1.12.1; \
  chown -R flink:flink .;

# Configure container
COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 6123 8081
CMD ["help"]

# Use this for testing the container
# COPY hello /
# ENTRYPOINT ["/hello"]

